services:
  redis:
    image: redis:7-alpine
    container_name: fenix_redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: fenix_db
    restart: always
    environment:
      POSTGRES_DB: fenix
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: fenix
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: fenix_api
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

volumes:
  pgdata:
